### ISSUE TITLE
Builder does not compile in strict mode

### ISSUE THREAD

**Issue by David-Else** [slavik57/design-patterns#1]
Thanks for the videos and code, but I get:
```
src/app.ts(18,11): error TS2564: Property 'numberOfSlices' has no initializer and is not definitely assigned in the constructor.
src/app.ts(19,11): error TS2564: Property 'isThin' has no initializer and is not definitely assigned in the constructor.
src/app.ts(20,11): error TS2564: Property 'doughType' has no initializer and is not definitely assigned in the constructor.
```
On your builder.ts, can this be fixed? Not compiling in strict makes the example not usable for me, which is a shame as it would be the most usable example I can find, including my usual favourites:

https://refactoring.guru/design-patterns/builder/typescript/example
https://github.com/torokmark/design_patterns_in_typescript

**Comment by slavik57** [comment]
It's probably due to some change in the compiler since the time I recorded the video.
Try setting all the private fields to some default values (like undefined).
Not sure setting for 'undefined' will work in strict mode though.

```
export class PizzaBuilder {
  private numberOfSlices: number = undefined;
  private isThin: boolean = undefined;
  private doughType: DoughType = undefined;
  private toppings: Topping[] = [];
```

Another solution is setting some default values and adding another boolean for every field to specify whether it was set at least once.

**Comment by David-Else** [comment]
I have the solution, https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization
```
private numberOfSlices: number | undefined;
private isThin: boolean | undefined;
private doughType: DoughType | undefined;
```
I am sending a pull request.
